mainproject/instagram/urls.py
from django.urls import path
from instagram.views import LoginView, UserRegistrationView, UserView, ProfileView, CreatePageView, LogoutView, CreateContentView, DeleteContentView, UpdateContentView
urlpatterns=[
    path('login/',
     LoginView.as_view(),
     name='login'),
     path('userregistration/',
         UserRegistrationView.as_view(),
         name='userregistration'),
     path('user/',
         UserView.as_view(),
         name='user'),
     path('profile/',
         ProfileView.as_view(),
         name='profile'),
     path('createpage/', 
          CreatePageView.as_view(),
          name='createpage'),
     path('logout/',
          LogoutView.as_view(),
          name='logout'),
     path('createcontent/',
          CreateContentView.as_view(),
          name='createcontent'),
     path('updatecontent/<int:id>/',
          UpdateContentView.as_view(),
          name='updatecontent'),
     path('deletecontent/',
          DeleteContentView.as_view(),
          name='deletecontent'),

]

mainproject/mainproject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('instagram.urls')),
]

mainproject/instagram/models.py
from django.db import models

class UserInfoModel(models.Model):
    name=models.CharField(max_length=25)
    email=models.EmailField(max_length=15, blank=False)
    dateofbirth=models.DateField(max_length=25)
    password=models.CharField(max_length=15) 
class LoginModel(models.Model):
    name=models.CharField(max_length=25)
    password=models.CharField(max_length=15)
class ContentModel(models.Model):
    title=models.CharField(max_length=25)
    image=models.ImageField()
    content=models.CharField(max_length=250)
    created=models.DateTimeField(auto_now_add=True)
    updated=models.DateTimeField(auto_now_add=True)

mainproject/instagram/forms.py
from django import forms
from .models import ContentModel


class ContentForm(forms.ModelForm):
    class Meta:
        model=ContentModel
        fields='__all__'

mainproject/instagram/views.py
from django.shortcuts import render, redirect
from django.urls import reverse
from django.views.generic import TemplateView, View
from .models import UserInfoModel, ContentModel
from .forms import ContentForm

# class UserRegistrationView(CreateView): 
#     template_name='instagram/registration.html'
#     model=UserInfoModel
#     fields='__all__'
#     success_url='/user'
#     def post(self, request, *args, **kwargs):
#         Email=request.POST['email']
#         if UserInfoModel.objects.filter(email=Email):
#             return self.get(request, *args, **kwargs)
#         return super().post(request, *args, **kwargs)
class UserRegistrationView(TemplateView):
    template_name='instagram/registration.html'
    def post(self, request, *args, **kwargs):
        UserInfoModel.objects.create(name=self.request.POST.get('name',None), 
                                     email=self.request.POST.get('email',None), 
                                     dateofbirth=self.request.POST.get('dateofbirth',None), 
                                     password=self.request.POST.get('password',None))
        # print(self.request.POST.get('name',None))
        # print(self.request.POST.get('email',None))
        # print(self.request.POST.get('dateofbirth',None))
        # print(self.request.POST.get('password',None))
        return redirect(reverse('login'))
        

    
    
    

class LoginView(TemplateView):
    template_name='instagram/login.html'
    def post(self, request, *args, **kwargs):
        Email=request.POST['email']
        password=request.POST['password']
        user = UserInfoModel.objects.filter(email=Email).first()
        if user:
            request.session['uid']=user.id
            return redirect(reverse('profile'))
        return self.get(request, *args, **kwargs)
    

class ProfileView(TemplateView):
    template_name='instagram/profile.html'
    def get(self, request, *args, **kwargs):
        u_id=request.session.get('uid')  
        try:
            user=UserInfoModel.objects.filter(id=u_id).first()
            if not user:
                return redirect(reverse('login'))
        except:
            return redirect(reverse('error'))
        kwargs['user']=user
        return super().get(request, *args, **kwargs) 


class LogoutView(View):
    def get(self, request, *agrs, **kwargs):
        u_id=request.session.get('uid')
        user=UserInfoModel.objects.filter (id=u_id).first()
        if user:
            del request.session['uid']
        return redirect(reverse('login'))


    # def get_context_data(self,**kwargs):
    #     print('name')
    #     user=kwargs['user']
    #     print(user.id) 
    #     print(user.dateofbirth)
    #     print(user.password)
    #     context={'user':user}
    #     kwargs.update(context)
    #     return kwargs

class CreatePageView(TemplateView):
    template_name='instagram/page.html'
    def get(self, request, *agrs, **kwargs):
        # ContentModel.objects.create(Title=self.request.POST.get('Title',None),
        #                             Image=self.request.POST.get('Image',None), 
        #                             Content=self.request.POST.get('Content',None),)
        return super().get(request, *agrs, **kwargs)

class CreateContentView(TemplateView):
    template_name='instagram/create_content.html'
    def post(self, request, *args, **kwargs):
        ContentModel.objects.create(title=self.request.POST.get('Title',None),
                                    image=self.request.POST.get('Image',None),
                                    content=self.request.POST.get('Content',None),
                                    created=self.request.POST.get('Create',None),
                                    updated=self.request.POST.get('Update',None),)
        return redirect(reverse('createpage'))
     
    def get_context_data(self, **kwargs):
        context = {
            'form': ContentForm
        }
        kwargs.update(context)
        return super().get_context_data(**kwargs)

class UpdateContentView(TemplateView):
    template_name='instagram/update_content.html'
    form_class=ContentForm
        
    def get_context_data(self, **kwargs):
        data=ContentModel.objects.get(id=self.kwargs['id'])
        form=self.form_class(instance=data)
        context={
            'form':form
        }
        kwargs.update(context)
        return super().get_context_data(**kwargs)
    def post(self, request, *args, **kwargs):
        data=ContentModel.objects.get(id=self.kwargs['id'])
        form=self.form_class(request.POST, instance=data)
        if form.is_valid():
            form.save() 
            return redirect(reverse('createpage'))
    #     d_id=kwargs.get('id')
    #     data=ContentModel.objects.get(id=d_id)
    #     context={'data':data}
    #     kwargs.update(context)
    #     return kwargs 
    # def POST(self, request, *agrs, **kwrgs):
    #     s_id= kwrgs.get('id')
    #     ContentModel.objects.filter(id=s_id).update()


class DeleteContentView(TemplateView):
    template_name='instagram/delete_content.html'
    def get(self, request, *args, **kwargs):
        
        return super().get(request, *args, **kwargs)   
        

class UserView(TemplateView):
    template_name='instagram/user.html'
    def get_context_data(self, **kwargs):
        some=UserInfoModel.objects.all()
        context={'page':some}
        kwargs.update(context)
        return super().get_context_data(**kwargs)

 

mainproject/instagram/templates/instagram/create_content.html
<html>
    <head>
        <title>
            Content
        </title>
    </head>
    <body>
        <form method="post">
            {%csrf_token%}
            <p><label for="id_Title">Title:</label> 
            <input type="text" name="Title" maxlength="15" required id="id_Title"></p>
            <p><label for="id_Image">Image:</label> 
            <input type="file" name="Image" accept="image/*" required id="id_Image"></p>
            <p><label for="id_Content">Content:</label> 
            <textarea name="Content" cols="40" rows="10" maxlength="5000" required id="id_Content"></textarea></p>
            <input type='submit' name="Submit">
            </form> 
    </body>
</html>

mainproject/instagram/templates/instagram/delete_content.html
<html>
    <head>
        <title>
            Delete
        </title>
        <body>
            <form method="post"></form>
            <!-- <p id="button"> </p>
            <p>Are you sure you want to delete content?</p> -->
            <button onclick='myFunction()'>Confirm</button>
            <script>
                function myFunction(){
                    confirm('Are you sure? do you really want to delete these records?')
                }
            </script>
        </form>
        </body>
    </head>
</html>

mainproject/instagram/templates/instagram/error.html
<html>
   <head>
    <title>
        Error
    </title>
   </head> 
   <body>
    <h2>User does not exist</h2>
   </body>
</html>

mainproject/instagram/templates/instagram/login.html
<html>
<head>
<title>
	Instagram Login
</title>
<style>
	body{
		text-align: center;
	}
	body{

  margin-top: 150px;
  margin-bottom: 100px;
  margin-right: 150px;
  margin-left: 80px;
	}
</style>
<body>
	<h1> Instagram </h1> 
	<form  method="post">
		{%csrf_token%}
		<label for="fname">Email:</label><br>
		<input type="email" name="email"> <br>
		<label for="lname">password:</label><br>
		<input type="password"> <br> <br>
		<input type="submit" value="login"> 
	</form>
	
</body>
</head>
</html>

mainproject/instagram/templates/instagram/logout.html
<html>
    <head>
        <title>
            Error
        </title>
    </head>
    <body>
        {{ Logout }}
    </body>
</html>

mainproject/instagram/templates/instagram/page.html
<html>
    <head>
        <title>
            Pages
        </title>
    </head>
    <body>
        <p>{{ pages }}</p>
    </body>
</html>

mainproject/instagram/templates/instagram/profile.html
<html>
    <head>
        <title>Profile</title>
    </head>
    <body>
        <p>{{ user.name }}</p>
        <p>{{ user.dateofbirth}}</p>
        <p>{{ user.password}}</p>
    </body>
</html>

mainproject/instagram/templates/instagram/registration.html
<html>
	<head>
		<title>
			Create Acconunt
		</title>
		</head>
		<script> </script>
		<style>
			body{
				text-align: center;
				padding-top: 50px;
                padding-right: 50px;
                padding-bottom: 50px;
                padding-left: 50px;
			}
	
			body{
                text-align: center;
				margin-top: 150px;
                margin-bottom: 100px;
                margin-right: 150px;
                margin-left: 80px;
			}
		</style>
		<body>
			<h1>{{page}}</h1>
			<form method="POST">
                {% csrf_token %}
				<p><label for="id_name">Name:</label> <input type="text" name="name" maxlength="25" required id="id_name"></p>
				<p><label for="id_email">Email:</label> <input type="email" name="email" maxlength="25" required id="id_email"></p>
				<p><label for="id_dateofbirth">Dateofbirth:</label> <input type="date" name="dateofbirth" required id="id_dateofbirth"></p>
				<p><label for="id_password">Password:</label> <input type="password" name="password" maxlength="15" required id="id_password"></p>		
				<!-- s -->
				<button onclick='myFunction()'>Create Account</button>
			</form>
			<script>
				function myFunction(){
					alert('Fill the data is before your submit')
				}
			</script>
		</body>
</html>

mainproject/instagram/templates/instagram/update_content.html
<html>
    <head>
        <title>
            Update
        </title>
        <body>
            <form method="post">
                {%csrf_token%}
                {{form.as_p}}
            <button type="submit">Update</button>                                                       
        </form>
        </body>
    </head>
</html>

mainproject/instagram/templates/instagram/user.html
<html>
	<head>
		<title>
			Create Acconunt
		</title>
		<script> </script>
		<!-- <style>
			body{
				padding-top: 50px;
                padding-right: 50px;
                padding-bottom: 50px;
                padding-left: 50px;
			}
	
			body{
                text-align: center;
				margin-top: 150px;
                margin-bottom: 100px;
                margin-right: 150px;
                margin-left: 80px;
			}
		</style> -->
		<body>
			{% for i in page %}
			<li>{{i.name}}</li>
			<li>{{i.email}}</li>
			<li>{{i.dateofbirth}}</li>
			<li>{{i.password}}</li><br>
			{% endfor %}
         </body>  
</html>